// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockTrackingService.proto

// Protobuf Java Version: 3.25.1
package org.example;

public interface StockQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockQueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_name = 1;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 1;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();
}
