// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockTrackingService.proto

// Protobuf Java Version: 3.25.1
package org.example;

public interface StockItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 product_id = 1;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>string product_name = 2;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 2;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();
}
