// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockTrackingService.proto

// Protobuf Java Version: 3.25.1
package org.example;

public interface StockStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 product_id = 1;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>string product_name = 2;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 2;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>int32 current_quantity = 3;</code>
   * @return The currentQuantity.
   */
  int getCurrentQuantity();

  /**
   * <pre>
   * stock available/ stock shortage
   * </pre>
   *
   * <code>string status = 4;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * stock available/ stock shortage
   * </pre>
   *
   * <code>string status = 4;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
